### ISSUE TITLE
break/continue are not scoped to while/until loops when in their conditions

### ISSUE THREAD

**Issue by Crestwave** [oilshell/oil#516]
```sh
osh$ while break; do :; done
  while break; do :; done
        ^~~~~
[ interactive ]:1: Loop and control flow can't be in different processes
osh$ while :; do while break; do :; done; echo a; break; done
osh$ 
```

From the POSIX specification (emphasis mine):

>  A loop shall enclose a break or continue command if the loop lexically encloses the command. A loop lexically encloses a break or continue command if the command is:
> ...
> - Contained in a compound-list associated with the loop (either in the compound-list of the loop's do-group or, **if the loop is a while or until loop, in the compound-list following the while or until reserved word**)

**Comment by andychu** [comment]
OK interesting, I think there are some test cases in smoosh that pertain to this.

links to smoosh results further down: https://www.oilshell.org/release/0.7.pre5/

The error message is definitely misleading.  Though I'm not sure at the moment what it will take to preserve that check and relax this one.

**Comment by Crestwave** [comment]
> OK interesting, I think there are some test cases in smoosh that pertain to this.
> 
> links to smoosh results further down: https://www.oilshell.org/release/0.7.pre5/

I couldn't find anything referring to it there, only using a function with `break` from a loop.

> The error message is definitely misleading. Though I'm not sure at the moment what it will take to preserve that check and relax this one.

I'm more worried about the fact that it scopes to the enclosing loop if there is one, potentially breaking scripts in dangerous ways silently. E.g., `del=1; while :; do while break; do :; done; del=0; break; done; (( del )) && printf 'Deleting all your files\n'`. Of course, this is far from a realistic scenario, but I did have a script end up doing nothing with no indication of what happened; this should have higher priority in my opinion.

**Comment by andychu** [comment]
OK it's interesting that it does the wrong thing when there are nested loops.

What was the context where you ran into this?  Or were you specifically testing OSH for bugs?

**Comment by Crestwave** [comment]
I was trying to run https://github.com/Crestwave/bf/blob/master/sh/bf1.sh.

**Comment by andychu** [comment]
OK this is fixed now.

Originally I was going to just copy in the tests, and leave it for later... however in the process of writing the tests I figured out what was wrong with the code, which turned out to be simple.

Thanks for testing it out and for the report!

**Comment by Crestwave** [comment]
Great! However, the script still doesn't work because of the use of bytes in the case statement. I actually couldn't find anything on POSIX on this, although Bash surely works with them.

**Comment by andychu** [comment]
OK interesting, that is closely related to #522 

Can you file a bug about it with a reproducible case?

**Comment by andychu** [comment]
Released with 0.7.pre6 : https://www.oilshell.org/release/0.7.pre6/
